package com.android.onlinehcmup.Support;

import android.app.Activity;

public class StaticTAG {
	public static Activity ACTIVITY;
	public static String TAG_PUBLIC_NEWS_LIST = "PUBLIC_NEWS_LIST_FRAGMENT";
	public static String TAG_PUBLIC_NEWS_DETAILS = "PUBLIC_NEWS_DETAILS_FRAGMENT";
	public static String TAG_PRIVATE_NEWS_LIST = "PRIVATE_NEWS_LIST_FRAGMENT";
	public static String TAG_PRIVATE_NEWS_DETAILS = "PRIVATE_NEWS_DETAILS_FRAGMENT";
	public static String TAG_STUDENT_INFO = "STUDENT_INFO_FRAGMENT";
	public static String TAG_STUDENT_COURSE = "STUDENT_COURSE_FRAGMENT";
	public static String TAG_STUDENT_CONTACT = "STUDENT_CONTACT_FRAGMENT";
	public static String TAG_STUDENT_CHANGE_PASSWORD = "STUDENT_CHANGE_PASSWORD_FRAGMENT";
	public static String TAG_STUDENT_EDIT_INFO = "STUDENT_EDIT_INFO_FRAGMENT";
	public static String TAG_STUDY_PROGRAM = "STUDY_PROGRAM_FRAGMENT";
	public static String TAG_REGISTER_CURRICULUM = "REGISTER_CURRICULUM_FRAGMENT";
	public static String TAG_REGISTER_CURRICULUM_RESULT = "REGISTER_CURRICULUM_RESULT_FRAGMENT";
	public static String TAG_REGISTER_CURRICULUM_RESULT_ALL = "REGISTER_CURRICULUM_RESULT_ALL_FRAGMENT";
	public static String TAG_REGISTER_CURRICULUM_DISACCUMULATED = "REGISTER_CURRICULUM_DISACCUMULATED_FRAGMENT";
	public static String TAG_REGISTER_CURRICULUM_REGISTER = "REGISTER_CURRICULUM_REGISTER_FRAGMENT";
	public static String TAG_SCHEDULE = "SCHEDULE_FRAGMENT";
	public static String TAG_SCHEDULE_EXAMINATE = "SCHEDULE_EXAMINATE_FRAGMENT";
	public static String TAG_MARK = "MARK_FRAGMENT";
}
